# Generated by Django 3.0.6 on 2020-11-23 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_body', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_features', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_fuel', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Miles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miles_on_car', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_transmission', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CarDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.CharField(max_length=13)),
                ('price', models.IntegerField()),
                ('car_brand', models.CharField(max_length=20)),
                ('car_model', models.CharField(max_length=30)),
                ('production_year', models.IntegerField(blank=True, null=True)),
                ('seating_capacity', models.IntegerField(blank=True, null=True)),
                ('engine_displacement', models.CharField(max_length=20)),
                ('car_image', models.ImageField(upload_to='car_image')),
                ('car_color', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=5000)),
                ('body_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_body_type', to='cars.Body')),
                ('car_miles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_car_miles', to='cars.Miles')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_fuel_type', to='cars.Fuel')),
                ('key_features', models.ManyToManyField(related_name='car_services', to='cars.Features')),
                ('owner_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('transmission_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_transmission_type', to='cars.Transmission')),
            ],
        ),
    ]
